version: '2'
services:
  rule_based_pipeline:
    image: rule_based_pipeline
    volumes:
      - ../../data:/app/data
      - ../../log:/app/server_logs
    ports:
      - 8000:8000
  be:
    build:
      context: ./
      dockerfile: dockerfile_dev
    command: sanic de.app --dev --host=0.0.0.0 --port=1300
    environment:
      - FILE_PATH=/data
    volumes:
      - ./src:/de
      - ../../data:/data
    ports:
      - 18000:1300
    depends_on:
      - rule_based_pipeline
